<?php
include "C:/xampp/htdocs/xampp/Azza/connects.php";
	
	$conn=new Databases;
	$conn = $conn->__construct();
	$DEPARTMENT = $_POST['DEPARTMENT1'];
	$SUBDEPARTMENT = $_POST['SUBDEPARTMENT1'];
	$NAME = $_POST['NAME1'];
	$ADDRNO = $_POST['ADDRNO1'];
	$PHONE = $_POST['PHONE1'];
	$EMAIL = $_POST['EMAIL1'];
	$PROVINCE = $_POST['PROVINCE1'];
	$DISTRICT = $_POST['DISTRICT1'];
	$SUBDISTRICT = $_POST['SUBDISTRICT1'];
	$ZIPCODE = $_POST['ZIPCODE1'];
	$CUSTOMER_ID=$_POST['CUSTOMER_ID'];
$sql = "INSERT INTO users (DEPARTMENT,SUBDEPARTMENT,NAME,PHONE,ADDRNO,EMAIL,PROVINCE,DISTRICT,SUBDISTRICT,ZIPCODE,CUSTOMER_ID) VALUES ('$DEPARTMENT','$SUBDEPARTMENT','$NAME','$PHONE','$ADDRNO','$EMAIL','$PROVINCE','$DISTRICT','$SUBDISTRICT','$ZIPCODE','$CUSTOMER_ID')";
	mysqli_query($conn, $sql);
	
	?>