<?php
	
	include "C:/xampp/htdocs/xampp/Azza/connects.php";
	
	$conn=new Databases;
	$conn = $conn->__construct();

	$DATE = $_POST["DATE"];
	$TIME = $_POST["TIME"];
	$AMOUNT = $_POST["AMOUNT"];
	$JOB = $_POST["JOB"];
	$EQUIPMENT = $_POST["EQUIPMENT"];
	$USER = $_POST['USER'];
	$PROVOICE = $_POST["PROVINCE"];
	$DISTRICT = $_POST["DISTRICT"];
	$SUBDISTRICT = $_POST["SUBDISTRICT"];
	$ZIPCODE = $_POST['ZIPCODE'];
	$CONTACT = $_POST['CONTACT'];
	$DEPARTMENT = $_POST['DEPARTMENT'];
	$NAME = $_POST['NAME'];
	$PHONE = $_POST['PHONE'];
	$EMAIL = $_POST['EMAIL'];
	$DEALER = $_POST["DEALER"];
	$WE =$_POST["WE"];
	$SUPPLIER = $_POST["SUPPLIER"];
	
	$sql = "INSERT INTO customer (CREATE_DATE,TIME,AMOUNT,JOB,EQUIPMENT,USER,PROVINCE,DISTRICT,SUBDISTRICT,ZIPCODE,CONTACT,DEPARTMENT,NAME,PHONE,EMAIL,DEALER,WE,SUPPLIER) VALUES 			('$DATE','$TIME','$AMOUNT','$JOB','$EQUIPMENT','$USER','$PROVOICE','$DISTRICT','$SUBDISTRICT',$ZIPCODE,'$CONTACT','$DEPARTMENT','$NAME','$PHONE','$EMAIL','$DEALER','$WE','$SUPPLIER')";	
	mysqli_query($conn, $sql);

?>