<?php
	
	include "C:/xampp/htdocs/xampp/Azza/connects.php";
	
	$conn=new Databases;
	$conn = $conn->__construct();
	
	$DATE = $_POST["DATE"];
	$REF_NO = str_replace("/","",$_POST[DATE]);
	
	$TIME = $_POST["TIME"];
	$AMOUNT = $_POST["AMOUNT"];
	$PROJECT = $_POST["PROJECT"];
	$EQUIPMENT = $_POST["EQUIPMENT"];
	$USER = $_POST['USER'];
	$BRANDNAME = $_POST['BRANDNAME'];
	$SERIES = $_POST['SERIES'];
	$LOGO = $_POST['LOGO'];
	$GOODS = $_POST['GOODS'];
	$LOGOS = $_POST["LOGO"]." ".$_POST["GOODS"];
	$PROVOICE = $_POST["PROVINCE"];
	$DISTRICT = $_POST["DISTRICT"];
	$SUBDISTRICT = $_POST["SUBDISTRICT"];
	$ZIPCODE = $_POST['ZIPCODE'];
	$CONTACT = $_POST['CONTACT'];
	$DEPARTMENT = $_POST['DEPARTMENT'];
	$NOTENAME = $_POST['NOTENAME'];
	$PHONE = $_POST['PHONE'];
	$EMAIL = $_POST['EMAIL'];
	$DEALER = $_POST["DEALER"];
	$WE =$_POST["WE"];
	$SUPPLIER = $_POST["SUPPLIER"];
	
	
	
	
	$sql = "INSERT INTO customer (REF_NO,CREATE_DATE,TIME,AMOUNT,PROJECT,EQUIPMENT,USER,BRANDNAME,SERIES,LOGO,PROVINCE,DISTRICT,SUBDISTRICT,ZIPCODE,CONTACT,DEPARTMENT,NAME,PHONE,EMAIL,DEALER,WE,SUPPLIER) VALUES 			('$REF_NO','$DATE','$TIME','$AMOUNT','$PROJECT','$EQUIPMENT','$USER','$BRANDNAME','$SERIES','$LOGOS','$PROVOICE','$DISTRICT','$SUBDISTRICT',$ZIPCODE,'$CONTACT','$DEPARTMENT','$NOTENAME','$PHONE','$EMAIL','$DEALER','$WE','$SUPPLIER')";	
	
	mysqli_query($conn, $sql);

?>